require "robby.plugins.autopairs"
-- require "robby.plugins.bufferline"
require "robby.plugins.cmp"
require "robby.plugins.comment"
require "robby.plugins.gitsigns"
require "robby.plugins.impatient"
require "robby.plugins.indent"
require "robby.plugins.lualine"
require "robby.plugins.nvim-tree"
require "robby.plugins.plugin_setup"
require "robby.plugins.toggleterm"
require "robby.plugins.treesitter"
